name: MGSurvE_DA
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - affine
  - attrs
  - beautifulsoup4
  - blosc
  - boost-cpp
  - branca
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - cartopy
  - cfitsio
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - contourpy
  - curl
  - cycler
  - deap
  - et_xmlfile
  - expat
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - freexl
  - gdal
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - gettext
  - giflib
  - hdf4
  - hdf5
  - icu
  - idna
  - jinja2
  - joblib
  - json-c
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libaec
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libgdal
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libjpeg-turbo
  - libkml
  - liblapack
  - libnetcdf
  - libnghttp2
  - libopenblas
  - libpng
  - libpq
  - libpysal
  - librttopo
  - libspatialindex
  - libspatialite
  - libsqlite
  - libssh2
  - libtiff
  - libwebp-base
  - libxcb
  - libxml2
  - libzip
  - libzlib
  - llvm-openmp
  - lz4-c
  - mapclassify
  - markupsafe
  - matplotlib-base
  - munch
  - munkres
  - ncurses
  - networkx
  - nspr
  - nss
  - numpy
  - openjpeg
  - openpyxl
  - openssl
  - osmnx
  - packaging
  - pandas
  - pcre2
  - pillow
  - pip
  - pixman
  - platformdirs
  - pooch
  - poppler
  - poppler-data
  - postgresql
  - proj
  - pthread-stubs
  - pyparsing
  - pyproj
  - pyshp
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - rasterio
  - readline
  - requests
  - rtree
  - scikit-learn
  - scipy
  - setuptools
  - shapely
  - six
  - snappy
  - snuggs
  - sqlite
  - threadpoolctl
  - tiledb
  - tk
  - typing-extensions
  - typing_extensions
  - tzcode
  - tzdata
  - unicodedata2
  - urllib3
  - wheel
  - xerces-c
  - xorg-libxau
  - xorg-libxdmcp
  - xyzservices
  - xz
  - zlib
  - zstd
  - pip:
      - anyio
      - appnope
      - argon2-cffi
      - argon2-cffi-bindings
      - arrow
      - asttokens
      - backcall
      - bleach
      - certifi
      - cffi
      - comm
      - compress-pickle
      - debugpy
      - decorator
      - defusedxml
      - dill
      - engineering-notation
      - executing
      - fastjsonschema
      - fiona
      - fqdn
      - geojson
      - haversine
      - ipykernel
      - ipython
      - ipython-genutils
      - ipywidgets
      - isoduration
      - jedi
      - jsonpointer
      - jsonschema
      - jupyter
      - jupyter-client
      - jupyter-console
      - jupyter-core
      - jupyter-events
      - jupyter-server
      - jupyter-server-terminals
      - jupyterlab-pygments
      - jupyterlab-widgets
      - lxml
      - matplotlib
      - matplotlib-inline
      - mgsurve
      - mistune
      - mpmath
      - nbclassic
      - nbclient
      - nbconvert
      - nbformat
      - nest-asyncio
      - notebook
      - notebook-shim
      - osmpythontools
      - pandocfilters
      - parso
      - pexpect
      - pickleshare
      - pointpats
      - prometheus-client
      - prompt-toolkit
      - psutil
      - ptyprocess
      - pure-eval
      - pycparser
      - pygments
      - pyrsistent
      - python-json-logger
      - pyyaml
      - pyzmq
      - qtconsole
      - qtpy
      - rfc3339-validator
      - rfc3986-validator
      - send2trash
      - sniffio
      - soupsieve
      - stack-data
      - sympy
      - terminado
      - tinycss2
      - tornado
      - traitlets
      - ujson
      - uri-template
      - vincenty
      - wcwidth
      - webcolors
      - webencodings
      - websocket-client
      - widgetsnbextension
      - xarray
